# Test your FastAPI endpoints

# The email, password, and any tokens in this file are DUMMY values for testing only.
# Tokens shown here are INVALID or EXPIRED — please generate your own valid credentials before running requests.

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

### Register a new user
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "password": "aSecurePassword123"
}

### Sign in a user to get an ID Token
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyBY0-K70rnulLzQKfqgBNHDV70Uz6fTsrg
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "password": "aSecurePassword123",
  "returnSecureToken": true
}


### Access the protected /users/me endpoint
GET http://127.0.0.1:8000/users/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXNtZS1pbnZlbnRvcnktbGl0ZSIsImF1ZCI6Im1zbWUtaW52ZW50b3J5LWxpdGUiLCJhdXRoX3RpbWUiOjE3NTYzOTIzODQsInVzZXJfaWQiOiJ5bWc1cWRuSWdzUXlMRjZiRUFuUmpRVkhnVTIzIiwic3ViIjoieW1nNXFkbklnc1F5TEY2YkVBblJqUVZIZ1UyMyIsImlhdCI6MTc1NjM5MjM4NCwiZXhwIjoxNzU2Mzk1OTg0LCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0dXNlcjFAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.pECFqWqTARyyX8NajYnMuPHo6_Z_yA2wIAscIjgPAJbn6UvF5mGQKBOE_m2FIYC0I9g0hBJL-ViCWvYNH8lGcdPhR6LH0qjcBOgSibAFaaz-zsg2v8mh0Sc33dtupZq6oVyl8GnVCDMogDoo5ilBSDuuQA35FwLncA5n1EzZALEm-yNL8kuVBVyDq-sF6BYQFb-Bk7VkVOMkCbJoJSPXeNa5w2WKI5X0vxnrRxcdh1dAf3c3ocNrYcf8zcPIBFjd9BUQg1Tz7X1gnM1O5KbJfd627hPHi1DBgf0ETtTUrDbUeY4NUVgXr50nFaDyu5PD9GLy1BwJypTiGNPoy5az0A",



### Create a new product
POST http://127.0.0.1:8000/products
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXNtZS1pbnZlbnRvcnktbGl0ZSIsImF1ZCI6Im1zbWUtaW52ZW50b3J5LWxpdGUiLCJhdXRoX3RpbWUiOjE3NTYzODc4MzcsInVzZXJfaWQiOiJ5bWc1cWRuSWdzUXlMRjZiRUFuUmpRVkhnVTIzIiwic3ViIjoieW1nNXFkbklnc1F5TEY2YkVBblJqUVZIZ1UyMyIsImlhdCI6MTc1NjM4NzgzNywiZXhwIjoxNzU2MzkxNDM3LCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0dXNlcjFAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.YnUzo4Z3KqhCpvA5kyOTerVYKfdG-gN7q1sItxbD0egeY0WR0ThTyyR9l0A_FMMgHmM9tUm0d2wrE1O1-2Hpu2xRLrugr_UesNVPeIZulHHjNXfu9S7OqMLVsu8OyiTTBsmNbOey9hCTuOyd_0H3L4rbh_p3ZMF7mVDFtcifKkXuT38lTBgRUyCc0Qmrf0pCb2VTvRV_gcHqNqScNRS4j0FjiAwo1RpKeiGxTIq-TmVM7Dxp8LqGoLIAjQ0s7HThkRAGJN8SPusRNEgNP2qKwaaINC1vJzF0ugcZ1fvC8pDSzOCZj-2WxCOA2C-w1B6sbtsvV6m3EvJDXbAf0Cq_MA
Content-Type: application/json

{
  "name": "Organic Green Tea3",
  "sku": "OGT-003",
  "category": "Beverages",
  "quantity": 100,
  "unit_price": 5.99
}

###

### Update a product (use the ID from above and version 1)
PUT http://127.0.0.1:8000/products/LvwKJWuSuol9ESyR2vzA
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXNtZS1pbnZlbnRvcnktbGl0ZSIsImF1ZCI6Im1zbWUtaW52ZW50b3J5LWxpdGUiLCJhdXRoX3RpbWUiOjE3NTYzODc4MzcsInVzZXJfaWQiOiJ5bWc1cWRuSWdzUXlMRjZiRUFuUmpRVkhnVTIzIiwic3ViIjoieW1nNXFkbklnc1F5TEY2YkVBblJqUVZIZ1UyMyIsImlhdCI6MTc1NjM4NzgzNywiZXhwIjoxNzU2MzkxNDM3LCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0dXNlcjFAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.YnUzo4Z3KqhCpvA5kyOTerVYKfdG-gN7q1sItxbD0egeY0WR0ThTyyR9l0A_FMMgHmM9tUm0d2wrE1O1-2Hpu2xRLrugr_UesNVPeIZulHHjNXfu9S7OqMLVsu8OyiTTBsmNbOey9hCTuOyd_0H3L4rbh_p3ZMF7mVDFtcifKkXuT38lTBgRUyCc0Qmrf0pCb2VTvRV_gcHqNqScNRS4j0FjiAwo1RpKeiGxTIq-TmVM7Dxp8LqGoLIAjQ0s7HThkRAGJN8SPusRNEgNP2qKwaaINC1vJzF0ugcZ1fvC8pDSzOCZj-2WxCOA2C-w1B6sbtsvV6m3EvJDXbAf0Cq_MA
Content-Type: application/json

{
    "quantity": 95,
    "version": 2
}

###

### Try a stale update (should fail with 409 Conflict)
PUT http://127.0.0.1:8000/products/cInl9VYnedGLbkfOIxUw
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXNtZS1pbnZlbnRvcnktbGl0ZSIsImF1ZCI6Im1zbWUtaW52ZW50b3J5LWxpdGUiLCJhdXRoX3RpbWUiOjE3NTYzODc4MzcsInVzZXJfaWQiOiJ5bWc1cWRuSWdzUXlMRjZiRUFuUmpRVkhnVTIzIiwic3ViIjoieW1nNXFkbklnc1F5TEY2YkVBblJqUVZIZ1UyMyIsImlhdCI6MTc1NjM4NzgzNywiZXhwIjoxNzU2MzkxNDM3LCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0dXNlcjFAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.YnUzo4Z3KqhCpvA5kyOTerVYKfdG-gN7q1sItxbD0egeY0WR0ThTyyR9l0A_FMMgHmM9tUm0d2wrE1O1-2Hpu2xRLrugr_UesNVPeIZulHHjNXfu9S7OqMLVsu8OyiTTBsmNbOey9hCTuOyd_0H3L4rbh_p3ZMF7mVDFtcifKkXuT38lTBgRUyCc0Qmrf0pCb2VTvRV_gcHqNqScNRS4j0FjiAwo1RpKeiGxTIq-TmVM7Dxp8LqGoLIAjQ0s7HThkRAGJN8SPusRNEgNP2qKwaaINC1vJzF0ugcZ1fvC8pDSzOCZj-2WxCOA2C-w1B6sbtsvV6m3EvJDXbAf0Cq_MA
Content-Type: application/json

{
    "quantity": 90,
    "version": 1
}

### Get Dashboard KPIs
GET http://127.0.0.1:8000/dashboard/kpis
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXNtZS1pbnZlbnRvcnktbGl0ZSIsImF1ZCI6Im1zbWUtaW52ZW50b3J5LWxpdGUiLCJhdXRoX3RpbWUiOjE3NTYzOTI0NDcsInVzZXJfaWQiOiJ5bWc1cWRuSWdzUXlMRjZiRUFuUmpRVkhnVTIzIiwic3ViIjoieW1nNXFkbklnc1F5TEY2YkVBblJqUVZIZ1UyMyIsImlhdCI6MTc1NjM5MjQ0NywiZXhwIjoxNzU2Mzk2MDQ3LCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0dXNlcjFAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.d2GgPNYRsJvA3len9gK2tlQRJNCmk9yqGXDi6p8rbDTQIkseqMdmzd2cyoKXIAPuDjqXs573G4eeIJBo2humG65dOMmCH7voNIgK624zD_ibNmRWntmvM-zFcYYhjcFtb_xC75jV19dx8hnLCzT9H_gRgIKPvoZJwLFupWU-ak2cNfhwOAaVgjR6OnEyiYdO9gB_CW2okF3W0Zt_315WXlWfZNUjFpgv2CdqyijEwPQtU-5zZLEsNNijLWah_PZNN5o46YaUsUPFtmXgR0knz46sSw2xUDAlMiYU0xZlOqr6x3uvbspoiTGx4zbRM7ksFXoynhxUoM1Em8UqnX1IvQ


### Import products from CSV file
POST http://127.0.0.1:8000/products/import/csv
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyZTg4M2NjNDY2M2E2MzMyYWRhNmJjMWU0N2YzZmY1ZTRjOGI1ZDciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXNtZS1pbnZlbnRvcnktbGl0ZSIsImF1ZCI6Im1zbWUtaW52ZW50b3J5LWxpdGUiLCJhdXRoX3RpbWUiOjE3NTYzOTI0NDcsInVzZXJfaWQiOiJ5bWc1cWRuSWdzUXlMRjZiRUFuUmpRVkhnVTIzIiwic3ViIjoieW1nNXFkbklnc1F5TEY2YkVBblJqUVZIZ1UyMyIsImlhdCI6MTc1NjM5MjQ0NywiZXhwIjoxNzU2Mzk2MDQ3LCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0dXNlcjFAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.d2GgPNYRsJvA3len9gK2tlQRJNCmk9yqGXDi6p8rbDTQIkseqMdmzd2cyoKXIAPuDjqXs573G4eeIJBo2humG65dOMmCH7voNIgK624zD_ibNmRWntmvM-zFcYYhjcFtb_xC75jV19dx8hnLCzT9H_gRgIKPvoZJwLFupWU-ak2cNfhwOAaVgjR6OnEyiYdO9gB_CW2okF3W0Zt_315WXlWfZNUjFpgv2CdqyijEwPQtU-5zZLEsNNijLWah_PZNN5o46YaUsUPFtmXgR0knz46sSw2xUDAlMiYU0xZlOqr6x3uvbspoiTGx4zbRM7ksFXoynhxUoM1Em8UqnX1IvQ
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="sample.csv"

< ./sample.csv
--boundary--